from typing import List, Optional
from pydantic import BaseModel, Field
from .user_schema  import UserProfile
from .scheme_schema import Scheme

class SchemeRecommendationRequest(BaseModel):
    query: str = Field(..., examples=["I am a 20-year-old engineering student from Karnataka with an annual family income of 2 lakh."])   
    existing_profile: Optional[UserProfile] = None 

class SchemeRecommendationResponse(BaseModel):
    profile_summary: UserProfile = Field(..., description="The user profile as understood by the system so far.")
    eligible_schemes: List[Scheme] = Field(..., description="List of schemes the user is eligible for based on known data.")
    documents_needed: List[str] = Field(default_factory=list, description="De-duplicated list of required documents.")
    missing_info: List[str] = Field(default_factory=list, description="Fields the system needs the user to provide next.")
    system_message: str = Field(..., description="A friendly message generated by the AI to reply to the user.")